defaults:
  - _self_

hydra:
  output_subdir: null

model:
  name: "ordinal_progressive_sd_ip"
  embedding_dim: 768
  conditioning_dim: 768
  base_channels: 320
  num_res_blocks: [2, 2, 2, 2]
  attention_heads: 8
  cfg_drop_prob: 0.1
  latent_channels: 4
  use_pretrained_vae: true
  pretrained_vae_path: "CompVis/stable-diffusion-v1-4"
  pretrained_unet_path: "CompVis/stable-diffusion-v1-4"
  image_encoder_path: "openai/clip-vit-large-patch14"
  num_image_tokens: 16
  image_scale: 1.0
  use_frequency_strategy: true
  use_image_projection_plus: true
  blur_kernel_size: 11
  blur_sigma: 15.0

  frequency_dominant_scale: 0.5
  frequency_non_dominant_scale: 1.5

  ordinal_embedder:
    type: "aoe"
    num_classes: 4
    interpolation_steps: 101
    aoe:
      delta_scale: 0.05

optimizer:
  name: "adamw"
  lr: 1e-4
  weight_decay: 0.001
  betas: [0.9, 0.999]

scheduler:
  name: "cosine"
  warmup_epochs: 2
  max_epochs: 150
  min_lr: 1e-6

dataset:
  dataset_path: /home/umut_dundar/repositories/progressive-stable-diffusion/data/limuc/processed_data_copy
  batch_size: 32
  num_workers: 22
  persistent_workers: true
  prefetch_factor: 2
  image_size: 256
  num_classes: 4
  sampler: "class_balanced"
  return_structure_images: true
  augmentation:
    flip: true
    rotation: 5
    center_crop: 224
    perspective: 0.2


training:
  max_epochs: 150
  log_every_n_steps: 50
  gradient_clip_val: 1.0
  accumulate_grad_batches: 2
  precision: "16-mixed"
  accelerator: "gpu"
  devices: 1
  strategy: "auto"
  seed: 42
  ema_decay: 0.999
  update_starting_at_step: 100
  update_every_n_steps: 4
  use_min_snr_weighting: true
  use_compile: false
  compile_mode: "reduce-overhead"
  gradient_checkpointing: true
  noise_offset: 0.0


wandb:
  project: "prog-disease-generation-ip"
  run_name: "dominant_1_nondominant_1_aoe_noblur_ip"
  log_samples_every_n_steps: 50
  offline: False

diffusion:
  noise_schedule: "linear"
  beta_start: 0.00085
  beta_end: 0.012
  num_train_timesteps: 1000
  sampling_steps: 50
  guidance_scale: 1.0
  min_snr_gamma: 1.0
  ema_update_interval: 1
